---
language: ruby
sudo: required
services:
  - docker
script:
  - bundle exec rake $COMMAND
rvm: 2.2.3
env:
  - COMMAND=lint
  - COMMAND=metadata
  - COMMAND=spec PUPPET_VERSION=4.6.1
  - COMMAND=spec PUPPET_VERSION=4.5.2
  - COMMAND=spec PUPPET_VERSION=4.4.2
  - COMMAND=beaker BEAKER_set=centos-6-x64 PUPPET_INSTALL_VERSION=1.6.2 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-7-x64 PUPPET_INSTALL_VERSION=1.6.2 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=debian-7-amd64 PUPPET_INSTALL_VERSION=1.6.2 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=ubuntu-server-1404-x64 PUPPET_INSTALL_VERSION=1.6.2 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-6-x64 PUPPET_INSTALL_VERSION=1.5.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-7-x64 PUPPET_INSTALL_VERSION=1.5.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=debian-7-amd64 PUPPET_INSTALL_VERSION=1.5.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=ubuntu-server-1404-x64 PUPPET_INSTALL_VERSION=1.5.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-6-x64 PUPPET_INSTALL_VERSION=1.4.2 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-7-x64 PUPPET_INSTALL_VERSION=1.4.2 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=debian-7-amd64 PUPPET_INSTALL_VERSION=1.4.2 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=ubuntu-server-1404-x64 PUPPET_INSTALL_VERSION=1.4.2 PUPPET_INSTALL_TYPE=agent
